### ISSUE TITLE
Running on MacOS 10.12

### ISSUE THREAD

**Issue by hackgoofer** [rudrapoudel/imgannotation#2]
Can't import image.
Images are all greyed out. What is the expected input format here?

It said in the main.cpp file that you are expecting only 8 bit image, but the example image isn't 8 bit.

![screen shot 2017-06-06 at 9 23 48 pm](https://user-images.githubusercontent.com/1545487/26862244-7b56a2c2-4afe-11e7-989b-ec9d0ebd9464.png)

**Comment by hackgoofer** [comment]
Sorry. I figured it out. :D Do you mind if I submit a Pull Request for documentation? It might be helpful for people after me who are n00bs. :)

**Comment by rudrapoudel** [comment]
Thanks, I did!
